tools:
  exit_forfeit:
    signature: |
      finish  [<work_summary>]
    docstring: "This is a finish_tool. If  you think your task has already been completed, please use this tool to finish it."
    arguments: 
      - name: work_summary
        type: string
        description: "The summary of the work done to complete the task."
        required: true