tools:
  knowledge_search:
    signature: "knowledge_search <command> [<key_word>] "
    docstring: "This is a tool you can use to look up terms you are not very familiar with."
    arguments: 
      - name: command
        type: string
        description: "the word type you want print,e.g. 'Noun' or 'Verb'"
        required: true
      - name: key_word
        type: string
        description: "All the words you wish to output should be connected with commas.,e.g. 'Multiple logarithms,Single logarithm'"
        required: true
        argument_format: "--key_word {{value}}"
